### ISSUE TITLE
Erro ao tentar rodar o exemplo do dacumentação

### ISSUE THREAD

**Issue by JorgeDorio** [osmirmariano/ofx-convert#3]
# Ambiente
Node 12.22.12 e 18.13.0

# Tentativa de uso

```
const ofx = require('ofx-convertjs');

const json = { id: 1, name: 'json' };
const data = ofx.toOfx(json);

console.log(data);
```

# Erro

```
Object.keys(obj).forEach((name) => {
                    ^

ReferenceError: obj is not defined
    at Ofx.toOfx (/home/voluti/dev/testeOfx/node_modules/ofx-convertjs/lib/ofx.js:46:21)
    at Object.<anonymous> (/home/voluti/dev/testeOfx/index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
    
   ```

**Comment by giacomoquinalia** [comment]
Qual a versão que você está utilizando? Esse erro parece ser do código anterior a esse commit: https://github.com/osmirmariano/ofx-convert/commit/1ac87da0eddf9f19f1ab1c1ea30921d05c879cf5

**Comment by JorgeDorio** [comment]
`"ofx-convertjs": "^1.0.7"` apenas dei `npm i ofx-convertjs`

**Comment by JorgeDorio** [comment]
> Esse erro parece ser do código anterior a esse commit: [1ac87da](https://github.com/osmirmariano/ofx-convert/commit/1ac87da0eddf9f19f1ab1c1ea30921d05c879cf5)

Alterei manualmente o código do arquivo `ofx.js` para o código presente no commit citado e deu certo.
